### ISSUE TITLE
The path to the stored variable is long and messy.

### ISSUE THREAD

**Issue by svolpe43** [stefanpenner/sync-disk-cache#15]
This is the path that it is currently using.

```
<user-name>/if-you-need-to-delete-this-open-an-issue-sync-disk-cache/<var>/adb3ce026a6501304227a5c2dd38d67a11b5b976
```

Why use username?
Why have this long dir that is a sentence?
Why can't TMPDIR env var overwrite everything up to the variable name?

I want to be able to set the TMPDIR to this.

```
export TMPDIR='/usr/share/application'
```

And then its stored as `/usr/share/application/<var>/adb3ce026a6501304227a5c2dd38d67a11b5b976`.

**Comment by stefanpenner** [comment]
> Why use username?

We noticed several users running into issues, specifically ones with multiple users sharing the same global tmp. The approach was to thus group by username

> Why have this long dir that is a sentence?

We wanted folks to correctly report related bugs, and this was the only clear opproach.

> Why can't TMPDIR env var overwrite everything up to the variable name?

The `TMPDIR` should allow the tmp directory `sync-disk-cache` uses to be re-rooted. This should be accomplish by  the fact that we use `require('os').tmpdir()` for the root.

The reason why changing `TMPDIR` alone does not change the complete path, was due to the issues described above.

That being said, I am very open to an additional env var, that allows the complete path to be renamed. For me though, that is relatively low priority, so It is unlikely I will get to it, but feel free to add such functionality.
